name: drinks-crm
region: fra
static_sites:
  - name: drinks-crm-web
    environment_slug: node-js
    github:
      repo: neyron357-boop/drinks_crm
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: out
    index_document: index.html
    catchall_document: index.html
